import {
  LayoutDashboard,
  BarChart3,
  Users,
  Stethoscope,
  CreditCard,
  ShieldCheck,
  Settings,
  CalendarDays,
  FileText,
  ClipboardPenLine,
  Pill,
  ListTodo,
  MessageSquare,
  Receipt,
  Wallet,
  AlertTriangle,
  BadgeCheck,
  ReceiptText,
  UserCheck,
  ClipboardList,
  FolderOpen,
  Building2,
  Hospital,
  Moon,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  BarChart3,
  Users,
  Stethoscope,
  CreditCard,
  ShieldCheck,
  Settings,
  CalendarDays,
  FileText,
  ClipboardPenLine,
  Pill,
  ListTodo,
  MessageSquare,
  Receipt,
  Wallet,
  AlertTriangle,
  BadgeCheck,
  ReceiptText,
  UserCheck,
  ClipboardList,
  FolderOpen,
  Building2,
  Hospital,
  Moon,
};

export function getNavIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? LayoutDashboard;
}
